name: scan__pay
description: "A new Flutter project."
publish_to: "none"

version: 1.0.21+30

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.12
  http: ^1.0.0
  shared_preferences: ^2.0.0
  intl: 0.20.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_functions: ^6.0.1
  cloud_firestore: ^6.0.2
  package_info_plus: ^9.0.0
  universal_html: ^2.2.4
  app_links: ^6.3.3
  webview_flutter: ^4.4.4
  webview_flutter_android: ^3.16.0
  firebase_app_check: ^0.4.1+2
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.1.0 # Added for environment variable management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/log3.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/log3.jpg
  remove_alpha_ios: true
  adaptive_icon_background: "#103C34"
  adaptive_icon_foreground: assets/log3.jpg
  web:
    generate: true
    image_path: assets/log3.jpg
