name: scan__pay
description: "A new Flutter project."
publish_to: "none"

version: 1.0.7+9

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  qr_flutter: ^4.0.0
  qr_code_scanner_plus: ^2.0.12
  http: ^1.0.0
  shared_preferences: ^2.0.0
  intl: 0.20.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_functions: ^6.0.1
  cloud_firestore: ^6.0.2
  package_info_plus: ^8.0.3
  crypto: ^3.0.5
  universal_html: ^2.2.4
  app_links: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/log3.jpg
    - shorebird.yaml

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/log3.jpg
  remove_alpha_ios: true
  adaptive_icon_background: "#103C34"
  adaptive_icon_foreground: assets/log3.jpg
